# This workflow will build OCCT
name: Build (All)

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/build_linux.yml
  mac:
    uses: ./.github/workflows/build_mac.yml
  wnt:
    uses: ./.github/workflows/build_wnt.yml
  wasm:
    uses: ./.github/workflows/build_wasm.yml
  android:
    uses: ./.github/workflows/build_android.yml
