name: Build (Ubuntu/GCC+Clang)
on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    runs-on: ubuntu-24.04
    steps:
    - name: Runner info
      run: |
        lscpu
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt.git
        fetch-depth: 1
    - name: Configure environment
      id: cfg
      run: |
        if [ "${{ matrix.compiler }}" == "gcc" ]; then
          echo "CC=gcc" >> $GITHUB_OUTPUT
          echo "CXX=g++" >> $GITHUB_OUTPUT
          echo "BUILD_SAMPLES_QT=ON" >> $GITHUB_OUTPUT
          echo "BUILD_Inspector=ON" >> $GITHUB_OUTPUT
        elif [ "${{ matrix.compiler }}" == "clang" ]; then
          echo "CC=clang" >> $GITHUB_OUTPUT
          echo "CXX=clang++" >> $GITHUB_OUTPUT
          echo "BUILD_SAMPLES_QT=OFF" >> $GITHUB_OUTPUT
          echo "BUILD_Inspector=OFF" >> $GITHUB_OUTPUT
        fi
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ${{ matrix.compiler }} cmake ninja-build \
          libfontconfig-dev libfreetype-dev \
          rapidjson-dev libdraco-dev \
          libx11-dev \
          libwayland-dev \
          libfreeimage-dev \
          libgl-dev libegl-dev libgles2-mesa-dev \
          tcllib tklib tcl-dev tk-dev \
          libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev \
          qtbase5-dev qtdeclarative5-dev qttools5-dev qttools5-dev-tools \
          qml-module-qtquick-controls2 qml-module-qtquick-templates2 \
          xvfb
    - name: Configure project
      env:
        CC: /usr/bin/${{ steps.cfg.outputs.CC }}
        CXX: /usr/bin/${{ steps.cfg.outputs.CXX }}
        OCCT_CONFIG: |
          set(BUILD_RELEASE_DISABLE_EXCEPTIONS OFF CACHE BOOL "")
          set(BUILD_DOC_Overview OFF CACHE BOOL "")
          set(BUILD_MODULE_Draw  ON CACHE BOOL "")
          set(BUILD_SAMPLES_QT ${{ steps.cfg.outputs.BUILD_SAMPLES_QT }} CACHE BOOL "")
          set(BUILD_Inspector ${{ steps.cfg.outputs.BUILD_Inspector }} CACHE BOOL "")
          set(USE_FREETYPE       ON CACHE BOOL "")
          set(USE_FREEIMAGE      ON CACHE BOOL "")
          set(USE_FFMPEG         ON CACHE BOOL "")
          set(USE_XLIB           ON CACHE BOOL "")
          set(USE_WAYLAND        ON CACHE BOOL "")
          set(USE_GLES2          ON CACHE BOOL "")
          set(USE_RAPIDJSON      ON CACHE BOOL "")
          set(USE_DRACO          ON CACHE BOOL "")
          set(CMAKE_BUILD_TYPE "Release")
          set(CMAKE_C_FLAGS    "-Werror")
          set(CMAKE_CXX_FLAGS  "-Werror -DQT_NO_DEPRECATED_WARNINGS")
          set(INSTALL_DIR      "${CMAKE_CURRENT_LIST_DIR}/occt-install" CACHE PATH "")
          set(3RDPARTY_QT_DIR  "/usr" CACHE PATH "")
      run: |
        ${{ matrix.compiler }} --version
        echo "${OCCT_CONFIG}" | tee ./occt-make.cmake
        cmake -S ./occt.git -B ./occt-make -G Ninja --toolchain "$PWD/occt-make.cmake"
    - name: Build project
      run: |
        cmake --build ./occt-make
    - name: Install build
      run: |
        cmake --install ./occt-make --prefix ./occt-install
    - name: Run DRAW
      run: |
        export LD_LIBRARY_PATH=$PWD/occt-install/lib
        export PATH=$PWD/occt-install/bin:$PATH
        xvfb-run -a DRAWEXE -c "dversion"
        xvfb-run -a DRAWEXE -c "pload ALL"
        xvfb-run -a DRAWEXE -c "pload VISUALIZATION; vdriver -load GL;   vinit; vglinfo;"
        xvfb-run -a DRAWEXE -c "pload VISUALIZATION; vdriver -load GLES; vinit; vglinfo;"

  genres:
    runs-on: ubuntu-24.04
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          flex bison libfl-dev \
          libwayland-dev wayland-protocols \
          xvfb
    - name: Configure project
      env:
        OCCT_CONFIG: |
          set(BUILD_RESOURCES    ON  CACHE BOOL "")
          set(BUILD_YACCLEX      ON  CACHE BOOL "")
          set(BUILD_DOC_Overview OFF CACHE BOOL "")
          set(BUILD_MODULE_Draw  OFF CACHE BOOL "")
          set(USE_FREETYPE       OFF CACHE BOOL "")
          set(USE_FREEIMAGE      OFF CACHE BOOL "")
          set(USE_XLIB           OFF CACHE BOOL "")
          set(USE_WAYLAND        ON CACHE BOOL "")
          set(USE_GLES2          OFF CACHE BOOL "")
          set(CMAKE_BUILD_TYPE  "Release")
      run: |
        echo "${OCCT_CONFIG}" | tee ./occt-make.cmake
        cmake -S ./occt.git -B ./occt-make --toolchain "$PWD/occt-make.cmake"
    - name: Regenerete yacclex resources
      run: |
        cmake --build ./occt-make --target yacclex
    - name: Generate diff
      run: |
        pushd ./occt.git
        nbChanged=`git diff --numstat -- src/ | wc -l`
        if [ "$nbChanged" != 0 ]; then
          echo "Error: regenerated source code files are different:"
          git diff --numstat -- src/ | awk '{print $3}'
          git diff > ../occt_genres_diff.patch
        fi
        popd
    - name: Upload diff
      uses: actions/upload-artifact@v6
      with:
        name: occt_genres_diff.patch
        path: occt_genres_diff.patch
        if-no-files-found: ignore
    - name: Check results
      run: |
        pushd ./occt.git
        nbChanged=`git diff --numstat -- src/ | wc -l`
        popd
        if [ "$nbChanged" != 0 ]; then
          echo "Error: regenerated source code files are different, see occt_genres_diff.patch."
          exit 1
        fi
