name: Build (macOS/Clang)
on:
  workflow_call:

jobs:
  build-mac-arm64:
    runs-on: macos-15
    steps:
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        brew update
        brew install \
          freetype freeimage
    - name: Configure project
      run: |
        BREW_PREFIX="$(brew --prefix)"
        mkdir "build"
        cmake -G Ninja -S . -B "./build" \
          -D CMAKE_BUILD_TYPE="Release" \
          -D INSTALL_DIR:PATH=install \
          -D BUILD_RELEASE_DISABLE_EXCEPTIONS:BOOL=OFF \
          -D BUILD_DOC_Overview:BOOL=OFF \
          -D BUILD_Inspector:BOOL=OFF \
          -D USE_FREETYPE:BOOL=ON \
          -D FREETYPE_DIR="$BREW_PREFIX" \
          -D USE_FREEIMAGE:BOOL=ON \
          -D FREEIMAGE_DIR="$BREW_PREFIX"
    - name: Build project
      run: |
        cmake --build "./build" --config Release
    - name: Install build
      run: |
        cmake --build "./build" --config Release --target install
