# This workflow performs Draw Harness regressions tests on Linux platform.
name: Test (Ubuntu/GCC)
on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        required: true
        default: ubuntu-24.04
      config:
        type: string
        required: true
        default: ubuntu-gcc
      # TODO take github.event.pull_request.base.ref in case of MR
      ref-branch:
        type: string
        required: false
        default: v7_7_x

jobs:
  # Build OCCT using the fastest configuration.
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
    - name: Runner info
      run: |
        lscpu
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt.git
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          g++ cmake ninja-build \
          libfontconfig-dev libfreetype-dev \
          rapidjson-dev libdraco-dev \
          libx11-dev libwayland-dev \
          libfreeimage-dev \
          libgl-dev libegl-dev libgles2-mesa-dev \
          tcllib tklib tcl-dev tk-dev \
          xvfb \
    - name: Configure project
      env:
        OCCT_CONFIG: |
          set(BUILD_RELEASE_DISABLE_EXCEPTIONS OFF CACHE BOOL "")
          set(BUILD_DOC_Overview OFF CACHE BOOL "")
          set(BUILD_MODULE_Draw  ON  CACHE BOOL "")
          set(BUILD_Inspector    OFF CACHE BOOL "")
          set(BUILD_SAMPLES_QT   OFF CACHE BOOL "")
          set(BUILD_USE_PCH      ON  CACHE BOOL "")
          set(USE_FREETYPE       ON  CACHE BOOL "")
          set(USE_FREEIMAGE      ON  CACHE BOOL "")
          set(USE_XLIB           ON  CACHE BOOL "")
          set(USE_WAYLAND        OFF CACHE BOOL "")
          set(USE_GLES2          ON  CACHE BOOL "")
          set(USE_RAPIDJSON      ON  CACHE BOOL "")
          set(USE_DRACO          ON  CACHE BOOL "")
          set(CMAKE_BUILD_TYPE "Release")
          set(INSTALL_DIR      "${CMAKE_CURRENT_LIST_DIR}/occt-install" CACHE PATH "")
      run: |
        g++ --version
        echo "${OCCT_CONFIG}" | tee ./occt-make.cmake
        cmake -S ./occt.git -B ./occt-make -G Ninja --toolchain "$PWD/occt-make.cmake"
    - name: Build project
      run: |
        cmake --build ./occt-make
    - name: Install build
      run: |
        cmake --install ./occt-make --prefix ./occt-install
    - name: Run DRAW
      run: |
        export LD_LIBRARY_PATH=$PWD/occt-install/lib
        export PATH=$PWD/occt-install/bin:$PATH
        xvfb-run -a DRAWEXE -c "dversion"
    - name: Pack install
      run: |
        anArchName=occt-${{ inputs.config }}.tar
        pushd ./occt-install
        tar -cf ../${anArchName} *
        popd
    - name: Upload build
      uses: actions/upload-artifact@v6
      with:
        name: occt-${{ inputs.config }}
        path: occt-${{ inputs.config }}.tar
        if-no-files-found: error

  # Run tests within subgroups to:
  # - provide granulated reports for different domains;
  # - speedup running on large number of small runners.
  tests:
    strategy:
      fail-fast: false
      matrix:
        group: [algo, algo-bugs, bop, heal, heal-bugs, v3d, opengl, webgl, xde, xde-bugs]
        include:
          # modeling data and algorithms
          - cmd: 'blend,chamfer,collections,cr,demo,draft,evolved,feat,fillet2d,gdt,geometry,lowalgos,mkface,nproject,offset,pipe,prism,mesh,hlr,thrusection'
            group: algo
          - cmd: 'bugs demo,fclasses,filling,mesh,modalg_1,modalg_2,modalg_3,modalg_4,modalg_5,modalg_6,modalg_7,modalg_8,modaldata_1,modaldata_2,modaldata_3'
            group: algo-bugs
          # boolean operations
          - cmd: 'boolean'
            group: bop
          # shape healing
          - cmd: 'heal'
            group: heal
          - cmd: 'bugs heal'
            group: heal-bugs
          # visualization
          - cmd: 'v3d,vselect'
            group: v3d
          - cmd: 'opengl,opengles3'
            group: opengl
          - cmd: 'webgl2'
            group: webgl
          # data exchange
          - cmd: 'caf,de,de_mesh,de_wrapper,persist,sewing,xcaf,xml'
            group: xde
          - cmd: 'bugs caf,iges,step,stlvrml,xde'
            group: xde-bugs
    runs-on: ${{ inputs.runs-on }}
    needs: build
    steps:
    - name: Runner info
      run: |
        lscpu
    - name: Clone Tree
      uses: actions/checkout@v6
      with:
        path: occt.git
        fetch-depth: 1
    - name: Clone Dataset
      uses: actions/checkout@v6
      with:
        path: occt.git/data/opencascade-dataset.git
        repository: gkv311/opencascade-dataset
        fetch-depth: 1
    # Extra packages: xwayland-run weston
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libfontconfig1 libfreetype6 libdraco8 libfreeimage3 \
          libegl1 libglapi-mesa libgl1 libgles2 \
          tcllib tklib tcl-thread \
          xvfb \
    # Install fr_FR locale for test bugs/xde/bug22898.
    - name: Install locales for xde tests
      if: (matrix.group == 'xde-bugs')
      run: |
        sudo apt-get install -y \
          locales language-pack-fr
        #echo "::group::Reconfigure locales"
        #export LANG="en_US.UTF-8"
        #export LC_ALL="en_US.UTF-8"
        #sudo dpkg-reconfigure locales
        #echo "::endgroup::"
        echo "::group::Available locales:"
        locale -a
        echo "::endgroup::"
        echo "::group::Active locale:"
        locale
        echo "::endgroup::"
    - name: Install fonts for v3d tests
      if: (matrix.group == 'v3d') || (matrix.group == 'opengl') || (matrix.group == 'webgl') || (matrix.group == 'algo') || (matrix.group == 'algo-bugs')
      run: |
        sudo apt-get install -y \
          fonts-dejavu \
          fonts-liberation fonts-liberation-sans-narrow \
          fonts-lexi-gulim \
          fonts-noto-cjk \
          fonts-freefont-ttf
    - name: Download build
      uses: actions/download-artifact@v8
      with:
        name: occt-${{ inputs.config }}
        path: occt-install
    - name: Unpack build
      run: |
        pushd ./occt-install
        tar -xvf ./occt-${{ inputs.config }}.tar
        popd
    - name: Run Tests
      env:
        EGL_BROWSER_LIBS: /usr/local/share/chromium/chrome-linux
        # these are located here when installed from `apt-get install chromium`
        #EGL_BROWSER_LIBS: /snap/chromium/current/usr/lib/chromium-browser
      run: |
        #source ./occt-install/bin/env.sh
        export LD_LIBRARY_PATH=$PWD/occt-install/lib
        export PATH=$PWD/occt-install/bin:$PATH
        export CASROOT=$PWD/occt.git
        export CSF_OCCTResourcePath=$CASROOT/src
        export CSF_OCCTSamplesPath=$CASROOT/samples
        export CSF_OCCTDataPath=$CASROOT/data
        export DRAWDEFAULT=$CSF_OCCTResourcePath/DrawResources/DrawDefault
        export DRAWHOME=$CSF_OCCTResourcePath/DrawResources
        export CSF_DrawPluginDefaults=$DRAWHOME
        # it is better to get rid of CSF_OCCTTestsPath
        export CSF_OCCTTestsPath=$CASROOT/tests
        # used by some XDE tests to switch healing parameters
        export CSF_IGESDefaults=$CSF_OCCTResourcePath/XSTEPResource
        export CSF_STEPDefaults=$CSF_OCCTResourcePath/XSTEPResource
        if [[ "${{ matrix.group }}" == "webgl" ]]; then
          export LD_PRELOAD=${EGL_BROWSER_LIBS}/libEGL.so:${EGL_BROWSER_LIBS}/libGLESv2.so
          xvfb-run -a DRAWEXE -c "pload VISUALIZATION; vdriver -load GLES; testgrid ${{ matrix.cmd }} -outdir $PWD/occt-results"
        else
          xvfb-run -a DRAWEXE -c "testgrid ${{ matrix.cmd }} -outdir $PWD/occt-results"
        fi
        lscpu > ./occt-results/cpuinfo.log
    # Check statistics and create warning/error annotations.
    - name: Check results
      id: results
      run: |
        testslog=./occt-results/tests.log
        nb_ok=`grep -o --count ': OK' $testslog || echo -n`
        nb_bad=`grep -o --count ': BAD' $testslog || echo -n`
        nb_failed=`grep -o --count ': FAILED' $testslog || echo -n`
        nb_skipped=`grep -o --count ': SKIPPED' $testslog || echo -n`
        nb_improved=`grep -o --count ': IMPROVED' $testslog || echo -n`
        nb_ko=$((nb_failed+nb_improved))
        echo "nb_ok=$nb_ok" >> $GITHUB_OUTPUT
        echo "nb_bad=$nb_bad" >> $GITHUB_OUTPUT
        echo "nb_failed=$nb_failed" >> $GITHUB_OUTPUT
        echo "nb_skipped=$nb_skipped" >> $GITHUB_OUTPUT
        echo "nb_improved=$nb_improved" >> $GITHUB_OUTPUT
        echo "nb_ko=$nb_ko" >> $GITHUB_OUTPUT

        echo "OK:       $nb_ok"       >> ./occt-results-summary.log
        echo "BAD:      $nb_bad"      >> ./occt-results-summary.log
        echo "IMPROVED: $nb_improved" >> ./occt-results-summary.log
        echo "FAILED:   $nb_failed"   >> ./occt-results-summary.log
        echo "SKIPPED:  $nb_skipped"  >> ./occt-results-summary.log

        if [[ $nb_failed != '0' ]]; then
          # find lines with failed cases, trim leading spaces, replace newlines into comma
          if [[ $nb_skipped != '0' ]]; then
            list_failed=`sed '/^Failed/,/^Skipped/!d;//d' $testslog | sed 's/^ *//g' | sed 's/^\|$/"/g'|paste -sd, -`
          else
            list_failed=`sed '/^Failed/,/^Total cases/!d;//d' $testslog | sed 's/^ *//g' | sed 's/^\|$/"/g'|paste -sd, -`
          fi
          echo "::error:: $nb_failed FAILED test(s) ($list_failed). Please check regressions."
        elif [[ $nb_improved != '0' ]]; then
          echo "::error:: $nb_improved IMPROVED test(s). Please validate results."
        elif [[ $nb_ok == '0' ]]; then
          echo "::error:: Invalid test results. Please check test grids."
        fi
        if [[ $nb_skipped != '0' ]]; then
          echo "::warning:: $nb_skipped SKIPPED test(s). Please check test data."
        fi
    # Prepare a separate report for failed test case
    # to spare time on downloading report with all test results.
    #
    # tests.log defines the following sections:
    # ```
    # Improvements:
    #   ...
    # Failed:
    #   ...
    # Skipped:
    #   ...
    # Total cases: ...
    # ```
    # and skips empty sections; so we use different 'sed' filters to collect results.
    - name: Collect failures
      id: failures
      if: |
        (steps.results.outputs.nb_failed != '0') ||
        (steps.results.outputs.nb_improved != '0')
      run: |
        testslog=./occt-results/tests.log
        nb_bad=`grep -o --count ': BAD' $testslog || echo -n`
        nb_failed=`grep -o --count ': FAILED' $testslog || echo -n`
        nb_skipped=`grep -o --count ': SKIPPED' $testslog || echo -n`
        nb_improved=`grep -o --count ': IMPROVED' $testslog || echo -n`
        list_failed=''
        if [[ $nb_failed != '0' && $nb_skipped != '0' ]]; then
          list_failed=`sed '/^Failed/,/^Skipped/!d;//d' $testslog`
        elif [[ $nb_failed != '0' ]]; then
          list_failed=`sed '/^Failed/,/^Total cases/!d;//d' $testslog`
        fi
        list_improved=''
        if [[ $nb_improved != '0' && $nb_failed != '0' ]]; then
          list_improved=`sed '/^Improvements/,/^Failed/!d;//d' $testslog`
        elif [[ $nb_improved != '0' && $nb_skipped != '0' ]]; then
          list_improved=`sed '/^Improvements/,/^Skipped/!d;//d' $testslog`
        elif [[ $nb_improved != '0' ]]; then
          list_failed=`sed '/^Improvements/,/^Total cases/!d;//d' $testslog`
        fi
        list_total=$list_failed
        if [[ ${#list_failed} -gt 0 && ${#list_improved} -gt 0 ]]; then
          list_total="${list_failed}
          ${list_improved}"
        elif [[ ${#list_failed} == 0 && ${#list_improved} -gt 0 ]]; then
          list_total=${list_improved}
        fi
        echo $list_total
        while read line; do
        read -r group grid casename <<< $line
          if [ ! -z "$group" ] && [ ! -z "$grid" ] && [ ! -z "$casename" ]
          then
            mkdir -p ./occt-results-bad/$group/$grid
            cp ./occt-results/$group/$grid/$casename* ./occt-results-bad/$group/$grid
          fi
        done <<< $list_total
        mkdir -p ./occt-results-bad
        cp ./occt-results/summary.html ./occt-results-bad/
    - name: Upload report with bad tests
      id: results_report_bad
      if: |
        (steps.results.outputs.nb_failed != '0') ||
        (steps.results.outputs.nb_improved != '0')
      uses: actions/upload-artifact@v6
      with:
        name: occt-${{ inputs.config }}-tests-${{ matrix.group }}-bad
        path: occt-results-bad
        if-no-files-found: error
    # Upload complete report, but filter out file artifacts
    # (temporary model files, which are supposed to be deleted by tests on completion).
    - name: Upload report with all tests
      id: results_report_all
      uses: actions/upload-artifact@v6
      with:
        name: occt-${{ inputs.config }}-tests-${{ matrix.group }}-all
        path: |
          occt-results
          !occt-results/**/*.bin
          !occt-results/**/*.brep
          !occt-results/**/*.cbf
          !occt-results/**/*.cmp
          !occt-results/**/*.gen
          !occt-results/**/*.xbf
          !occt-results/**/*.xml
          !occt-results/**/*.igs
          !occt-results/**/*.iges
          !occt-results/**/*.stp
          !occt-results/**/*.step
          !occt-results/**/*.stl
          !occt-results/**/*.wrl
          !occt-results/**/*.vrml
        if-no-files-found: error
    - name: Fetch reference results location
      id: reference
      if: (inputs.ref-branch != '')
      run: |
        refbranch=${{ inputs.ref-branch }}
        if [[ -n "$GITHUB_BASE_REF" ]]; then
          refbranch=$GITHUB_BASE_REF
        fi
        response=$(curl --silent --retry 5 --show-error \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ inputs.ref-branch }}&status=success")
        if [[ $response == '' ]]; then
          echo "Unexpected empty response. Retrying 1..."
          response=$(curl --silent --retry 5 --show-error \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ inputs.ref-branch }}&status=success")
        fi
        if [[ $response == '' ]]; then
          echo "Unexpected empty response. Retrying 2..."
          response=$(curl --silent --retry 5 --show-error \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=${{ inputs.ref-branch }}&status=success")
        fi
        run_id=$(echo "$response" | jq -r \
          --arg wfname "$GITHUB_WORKFLOW" \
          --arg wfrepo "${{ github.repository }}" \
          '.workflow_runs[] | select(.name==$wfname and .head_repository.full_name==$wfrepo) | .id' | head -n 1)
        created_at=$(echo "$response" | jq -r \
          --arg wfname "$GITHUB_WORKFLOW" \
          --arg wfrepo "${{ github.repository }}" \
          '.workflow_runs[] | select(.name==$wfname and .head_repository.full_name==$wfrepo) | .created_at' | head -n 1)
        echo "Found run id: $run_id; created_at: $created_at"
        echo "run_id=$run_id" >> $GITHUB_OUTPUT
        echo "created_at=$created_at" >> $GITHUB_OUTPUT
        if [[ $run_id == '' ]]; then
          echo "::warning::No run id found with reference test results"
        fi
    #- name: Download reference results
    #  env:
    #    GH_TOKEN: ${{ github.token }}
    #  run: |
    #    pushd ./occt.git
    #    gh run download ${{ steps.reference.outputs.run_id }} -n "occt-${{ inputs.config }}-tests-${{ matrix.group }}-all" -D "../occt-results-ref"
    #    popd
    # TODO do not fail on missing reference data
    - name: Download reference results
      if: (steps.reference.outputs.run_id != '')
      uses: actions/download-artifact@v8
      with:
        name: occt-${{ inputs.config }}-tests-${{ matrix.group }}-all
        path: occt-results-ref
        github-token: ${{ github.token }}
        run-id: ${{ steps.reference.outputs.run_id }}
    - name: Run testdiff with reference
      id: testdiff
      if: steps.reference.outputs.run_id != ''
      run: |
        res_ref=$PWD/occt-results-ref
        res_new=$PWD/occt-results
        export LD_LIBRARY_PATH=$PWD/occt-install/lib
        export PATH=$PWD/occt-install/bin:$PATH
        export CASROOT=$PWD/occt.git
        export CSF_OCCTResourcePath=$CASROOT/src
        export DRAWDEFAULT=$CSF_OCCTResourcePath/DrawResources/DrawDefault
        export DRAWHOME=$CSF_OCCTResourcePath/DrawResources
        export CSF_DrawPluginDefaults=$DRAWHOME
        DRAWEXE -b -c "testdiff {${res_new}} {${res_ref}}" | awk '{print "[INFO] " $0}'
        diff_log=`find $res_new -name "diff*.log"`
        diff_html=`find $res_new -name "diff*.html"`
        if [ ! -f $diff_log ] && [ ! -f $diff_html ]; then
          echo "::error::testdiff results not found"
          echo "status=false" >> $GITHUB_OUTPUT
          #exit 1
        else
          echo "status=true" >> $GITHUB_OUTPUT
        fi
    - name: Extract testdiff results
      id: testdiff_results
      if: |
        (steps.reference.outputs.run_id != '') &&
        (steps.testdiff.outputs.status == 'true')
      run: |
        out_dir=$PWD/occt-results-diff
        res_ref=$PWD/occt-results-ref
        res_new=$PWD/occt-results
        #res_ref_base=`basename $res_ref`
        #res_new_base=`basename $res_new`
        res_ref_base=occt-results-ref
        res_new_base=occt-results-new
        mkdir -p $out_dir
        mkdir -p $out_dir/$res_ref_base
        mkdir -p $out_dir/$res_new_base
        cpu_ref=`cat $res_ref/cpuinfo.log | grep "Model name" | cut -d: -f2 | xargs`
        cpu_new=`cat $res_new/cpuinfo.log | grep "Model name" | cut -d: -f2 | xargs`
        gpu_ref=`cat $res_ref/tests.log   | grep "GLdevice"   | cut -d: -f2 | xargs`
        gpu_new=`cat $res_new/tests.log   | grep "GLdevice"   | cut -d: -f2 | xargs`
        cp $res_ref/cpuinfo.log  $out_dir/$res_ref_base
        cp $res_ref/summary.csv  $out_dir/$res_ref_base
        cp $res_ref/summary.html $out_dir/$res_ref_base
        cp $res_ref/tests.log    $out_dir/$res_ref_base
        cp $res_new/cpuinfo.log  $out_dir/$res_new_base
        cp $res_new/summary.csv  $out_dir/$res_new_base
        cp $res_new/summary.html $out_dir/$res_new_base
        cp $res_new/tests.log    $out_dir/$res_new_base
        cpu_diff=''
        if [[ "$cpu_new" != "$cpu_ref" ]]; then
          cpu_diff=" Warning: CPU model is different (REF: $cpu_ref; NEW: $cpu_new)."
        fi
        gpu_diff=''
        if [[ "$gpu_new" != "$gpu_ref" ]]; then
          gpu_diff=" Warning: GLdevice is different (REF: $gpu_ref; NEW: $gpu_new)."
        fi
        echo -n "" > ./occt-results-warnings2.log
        diff_log=`find $res_new -name "diff*.log"`
        while IFS= read -r line; do
          if [[ -n "$line" && "$line" == IMAGE* ]]; then
            case_fullname=`echo "$line" | sed 's/IMAGE \([^:]*\) \([^:]*\) \([^:]*\):.*/\1 \2 \3/'`
            while read subline; do
              read -r group grid casename <<< $subline
              mkdir -p $out_dir/$res_ref_base/$group/$grid
              mkdir -p $out_dir/$res_new_base/$group/$grid
              cp $res_ref/$group/$grid/$casename* $out_dir/$res_ref_base/$group/$grid
              cp $res_new/$group/$grid/$casename* $out_dir/$res_new_base/$group/$grid
              # copy 'differs' and skip 'is similar', for which there is no diff image
              #if [[ "$subline" == *differs* ]]; then
              if ! cp $res_new/$group/$grid/diff-*$casename*.png $out_dir/$res_new_base/$group/$grid; then
                echo "Unable to find diff image for $group/$grid/$casename"
              fi
              echo -n "$line | " >> ./occt-results-warnings2.log
            done <<< $case_fullname
          elif [[ -n "$line" && "$line" == "Total IMAGE difference"* ]]; then
            echo -e "$line" >> ./occt-results-summary.log
            if [[ "$line" == "Total IMAGE difference: 0 / 0"* ]]; then
              echo "::error::testdiff haven't found matching test cases."
            elif [[ "$line" != "Total IMAGE difference: 0 /"* ]]; then
              echo -e "::warning::$line. ${cpu_diff}${gpu_diff}" >> ./occt-results-warnings.log
            fi
          elif [[ -n "$line" && "$line" == "Total CPU difference"* ]]; then
            echo -e "$line" >> ./occt-results-summary.log
          elif [[ -n "$line" && "$line" == "Total MEMORY difference"* ]]; then
            echo -e "$line" >> ./occt-results-summary.log
          fi
        done < "$diff_log"
        cp $res_new/diff-* $out_dir/$res_new_base
        if [[ -f ./occt-results-bad ]]; then
          cp -rf ./occt-results-bad/* $out_dir/$res_new_base
        fi
    - name: Upload report with differences
      id: testdiff_report
      if: |
        (steps.reference.outputs.run_id != '') &&
        (steps.testdiff.outputs.status == 'true')
      uses: actions/upload-artifact@v6
      with:
        name: occt-${{ inputs.config }}-tests-${{ matrix.group }}-diff
        path: occt-results-diff
        if-no-files-found: error
    - name: Set final job status
      run: |
        cat ./occt-results-summary.log
        if [[ -f ./occt-results-warnings.log ]]; then
          warns=$(cat ./occt-results-warnings.log)
          warns2=$(cat ./occt-results-warnings2.log)
          echo -e "${warns} Please check report: ${{ steps.testdiff_report.outputs.artifact-url }} | ${warns2}"
        fi
        if [[ "${{ steps.results.outputs.nb_failed }}" != '0' || "${{ steps.results.outputs.nb_improved }}" != '0' || "${{ steps.results.outputs.nb_ok }}" == '0' ]]; then
          exit 1
        fi
